from django.urls import path

from .views import (
    ComputadorCreateView,
    ComputadorDeleteView,
    ComputadorListView,
    ComputadorUpdateView,
    KitTabletCreateView,
    KitTabletDeleteView,
    KitTabletListView,
    KitTabletUpdateView,
    TabletCreateView,
    TabletDeleteView,
    TabletListView,
    TabletUpdateView,
)

app_name = "recursos"

urlpatterns = [
    path(
        route="computador-list/",
        view=ComputadorListView.as_view(),
        name="computador_list",
    ),
    path(
        route="computador-create/",
        view=ComputadorCreateView.as_view(),
        name="computador_create",
    ),
    path(
        route="computador-update/<uuid:pk>/",
        view=ComputadorUpdateView.as_view(),
        name="computador_update",
    ),
    path(
        route="computador-delete/<uuid:pk>/",
        view=ComputadorDeleteView.as_view(),
        name="computador_delete",
    ),
    path(
        route="tablet-list/",
        view=TabletListView.as_view(),
        name="tablet_list",
    ),
    path(
        route="tablet-create/",
        view=TabletCreateView.as_view(),
        name="tablet_create",
    ),
    path(
        route="tablet-update/<uuid:pk>/",
        view=TabletUpdateView.as_view(),
        name="tablet_update",
    ),
    path(
        route="tablet-delete/<uuid:pk>/",
        view=TabletDeleteView.as_view(),
        name="tablet_delete",
    ),
    path(
        route="kit_tablet-list/",
        view=KitTabletListView.as_view(),
        name="kit_tablet_list",
    ),
    path(
        route="kit_tablet-create/",
        view=KitTabletCreateView.as_view(),
        name="kit_tablet_create",
    ),
    path(
        route="kit_tablet-update/<uuid:pk>/",
        view=KitTabletUpdateView.as_view(),
        name="kit_tablet_update",
    ),
    path(
        route="kit_tablet-delete/<uuid:pk>/",
        view=KitTabletDeleteView.as_view(),
        name="kit_tablet_delete",
    ),
]
