from django.urls import path

from .views import (
    ComputadorCreateView,
    ComputadorDeleteView,
    ComputadorListView,
    ComputadorUpdateView,
    KitTabletCreateView,
    KitTabletDeleteView,
    KitTabletListView,
    KitTabletUpdateView,
    MesaTrabalhoCreateView,
    MesaTrabalhoDeleteView,
    MesaTrabalhoListView,
    MesaTrabalhoUpdateView,
    OculusVRCreateView,
    OculusVRDeleteView,
    OculusVRListView,
    OculusVRUpdateView,
    SalaReuniaoCreateView,
    SalaReuniaoDeleteView,
    SalaReuniaoListView,
    SalaReuniaoUpdateView,
    TabletCreateView,
    TabletDeleteView,
    TabletListView,
    TabletUpdateView,
)

app_name = "recursos"

urlpatterns = [
    path(
        route="computador-list/",
        view=ComputadorListView.as_view(),
        name="computador_list",
    ),
    path(
        route="computador-create/",
        view=ComputadorCreateView.as_view(),
        name="computador_create",
    ),
    path(
        route="computador-update/<uuid:pk>/",
        view=ComputadorUpdateView.as_view(),
        name="computador_update",
    ),
    path(
        route="computador-delete/<uuid:pk>/",
        view=ComputadorDeleteView.as_view(),
        name="computador_delete",
    ),
    path(
        route="tablet-list/",
        view=TabletListView.as_view(),
        name="tablet_list",
    ),
    path(
        route="tablet-create/",
        view=TabletCreateView.as_view(),
        name="tablet_create",
    ),
    path(
        route="tablet-update/<uuid:pk>/",
        view=TabletUpdateView.as_view(),
        name="tablet_update",
    ),
    path(
        route="tablet-delete/<uuid:pk>/",
        view=TabletDeleteView.as_view(),
        name="tablet_delete",
    ),
    path(
        route="kit-tablet-list/",
        view=KitTabletListView.as_view(),
        name="kit_tablet_list",
    ),
    path(
        route="kit-tablet-create/",
        view=KitTabletCreateView.as_view(),
        name="kit_tablet_create",
    ),
    path(
        route="kit-tablet-update/<uuid:pk>/",
        view=KitTabletUpdateView.as_view(),
        name="kit_tablet_update",
    ),
    path(
        route="kit-tablet-delete/<uuid:pk>/",
        view=KitTabletDeleteView.as_view(),
        name="kit_tablet_delete",
    ),
    path(
        route="oculus-vr-list/",
        view=OculusVRListView.as_view(),
        name="oculus_vr_list",
    ),
    path(
        route="oculus-vr-create/",
        view=OculusVRCreateView.as_view(),
        name="oculus_vr_create",
    ),
    path(
        route="oculus-vr-update/<uuid:pk>/",
        view=OculusVRUpdateView.as_view(),
        name="oculus_vr_update",
    ),
    path(
        route="oculus-vr-delete/<uuid:pk>/",
        view=OculusVRDeleteView.as_view(),
        name="oculus_vr_delete",
    ),
    path(
        route="mesa-trabalho-list/",
        view=MesaTrabalhoListView.as_view(),
        name="mesa_trabalho_list",
    ),
    path(
        route="mesa-trabalho-create/",
        view=MesaTrabalhoCreateView.as_view(),
        name="mesa_trabalho_create",
    ),
    path(
        route="mesa-trabalho-update/<uuid:pk>/",
        view=MesaTrabalhoUpdateView.as_view(),
        name="mesa_trabalho_update",
    ),
    path(
        route="mesa-trabalho-delete/<uuid:pk>/",
        view=MesaTrabalhoDeleteView.as_view(),
        name="mesa_trabalho_delete",
    ),
    path(
        route="sala-reuniao-list/",
        view=SalaReuniaoListView.as_view(),
        name="sala_reuniao_list",
    ),
    path(
        route="sala-reuniao-create/",
        view=SalaReuniaoCreateView.as_view(),
        name="sala_reuniao_create",
    ),
    path(
        route="sala-reuniao-update/<uuid:pk>/",
        view=SalaReuniaoUpdateView.as_view(),
        name="sala_reuniao_update",
    ),
    path(
        route="sala-reuniao-delete/<uuid:pk>/",
        view=SalaReuniaoDeleteView.as_view(),
        name="sala_reuniao_delete",
    ),
]
