# Generated by Django 4.2.13 on 2024-06-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oculusvr",
            options={
                "ordering": ["id"],
                "verbose_name": "Oculus VR",
                "verbose_name_plural": "Oculus VR",
            },
        ),
    ]
